city/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from city import views

urlpatterns = patterns('',
    url(r'^test/$', views.test ,name='test'),



)

play/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from play import views, api

urlpatterns = patterns('',
    url(r'^login/$', views.login ,name='login'),  
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^idea/$', views.idea ,name='idea'),


    url(r'^$', views.index ,name='index'),
    url(r'^event/$', views.event ,name='event'),
    url(r'^tmp_home/$', views.tmp_home ,name='tmp_home'),
   
    url(r'^(?P<city_name>\w+)/home/$', views.home ,name='home'),
    url(r'^(?P<city_name>\w+)/look_events/$', views.look_events ,name='look_events'),
    url(r'^(?P<city_name>\w+)/look_coupons/$', views.look_coupons ,name='look_coupons'),
    url(r'^(?P<city_name>\w+)/leaderboard/$', views.leaderboard ,name='leaderboard'),
    url(r'^(?P<city_name>\w+)/feeds/$', views.feeds ,name='feeds'),
    url(r'^(?P<city_name>\w+)/edit_profile/$', views.edit_profile ,name='edit_profile'),

)

play_palo_alto/urls.py
from django.conf.urls import patterns, include, url
#from tastypie.api import Api
#from play.api.resources import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^play_palo_alto/', include('play_palo_alto.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'', include('play_api.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('play.urls', namespace="play")),
    url(r'^(?P<city_name>\w+)/charity/', include('charity.urls', namespace="charity")),
    url(r'^(?P<city_name>\w+)/', include('city.urls', namespace="city")),
    url(r'^(?P<city_name>\w+)/shop/', include('shop.urls', namespace="shop")),
    url(r'^', include('city.urls', namespace="city")),
    url(r'', include('social_auth.urls')),
    #(r'^api/', include('play.api_urls', namespace="api")),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
)

charity/models.py
from django.db import models
from datetime import date
from django import forms
from django.contrib.auth.models import User,UserManager
from django.utils import timezone
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _
from play.utils import *
from social_auth.models import UserSocialAuth
from play import constants
from django.core.exceptions import *
import play.models
import shop.models
# Create your models here.
import requests
import datetime
from city.models import City

class Organization(models.Model):
    user=models.ForeignKey(User)
    city=models.ForeignKey(City, related_name='city_shop', default=None, null=True)
    title=models.CharField(max_length=100, null=True, default='Super Duper!')
    location=models.CharField(max_length=100, null=True)
    def __unicode__(self):  # Python 3: def __str__(self):
        return unicode(self.title) or u''

class Event(models.Model):
    title=models.CharField(max_length=100, null=True)
    description=models.TextField(max_length=500, null=True)
    location=models.CharField(max_length=100, null=True)
    picture_url=models.CharField(max_length=200, null=True, default='/static/img/stanford.png')
    experience=models.DecimalField(max_digits=5, decimal_places=0, null=True, default=0)
    #position = GeopositionField()
    challenge_event=models.CharField(max_length=50,choices=constants.CHALLENGE_EVENT, default='Event')
    points=models.DecimalField(max_digits=4, decimal_places=0)  
    participants = models.ManyToManyField('play.Player', default=None, null=True)
    event_type=models.CharField(max_length=50,choices=constants.TYPE, default=None)
    date=models.DateTimeField( null=True, default=None)
    organizer=models.ForeignKey(Organization)
    def __unicode__(self):  # Python 3: def __str__(self):
        return unicode(self.title) or u'' 

def assign_event_pic(sender, instance, created, **kwargs):
    if created:
        if instance.event_type=='Animals':
            instance.picture_url='/static/img/animal.png'
        if instance.event_type=='Food':
            instance.picture_url='/static/img/food.png'
        if instance.event_type=='Elders':
            instance.picture_url='/static/img/elder.png'
        if instance.event_type=='Art':
            instance.picture_url='/static/img/art.png'
        if instance.event_type=='Environment':
            instance.picture_url='/static/img/environment.png'
        if instance.event_type=='Shopping':
            instance.picture_url='/static/img/shopping.png'
        instance.save()
post_save.connect(assign_event_pic, sender=Event)

play/models.py
from django.db import models
from datetime import date
from django import forms
from django.contrib.auth.models import User,UserManager
from django.utils import timezone
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _
from utils import *
from social_auth.models import UserSocialAuth
import constants
from django.core.exceptions import *
import charity.models
import shop.models
# Create your models here.
import requests
import datetime
from city.models import City
#from social_auth.backends.pipeline.user import update_user_details
class Player(models.Model):
    user=models.ForeignKey(User)
    city=models.ForeignKey(City, related_name='city', default=None, null=True)
    custom_auth = forms.BooleanField(initial=False)
    token=models.CharField(max_length=100, null=True, default=None)
    score=models.DecimalField(max_digits=4, decimal_places=0, null=True, default=20)
    experience=models.DecimalField(max_digits=5, decimal_places=0, null=True, default=0)
    level=models.DecimalField(max_digits=4, decimal_places=0, null=True, default=0)
    picture_url=models.CharField(max_length=400, null=True, default='/static/img/avatar-1.png')
    facebook_pic=models.BooleanField(default=True)
    def __unicode__(self):  # Python 3: def __str__(self):
        return unicode(self.user) or u'' 


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Player.objects.create(user=instance)
        
post_save.connect(create_user_profile, sender=User)


class CouponHistory(models.Model):
    title=models.CharField(max_length=100, null=True)
    #coupon=models.ForeignKey(Coupon, related_name='coupon')
    shop=models.CharField(max_length=100, null=True)
    player=models.ForeignKey(Player)
    #shop=models.ForeignKey(Shop, related_name='created')


class EventHistory(models.Model):
    date=models.DateTimeField( null=True)
    title=models.CharField(max_length=100, null=True)
    #event_done=models.ForeignKey(Event, related_name='created')
    organization=models.CharField(max_length=100, null=True)
    player=models.ForeignKey(Player)
    points=models.DecimalField(max_digits=4, decimal_places=0)
    event_type=models.CharField(max_length=50,choices=constants.TYPE, default=None, null=True)
    #organization=models.ForeignKey(Organization, related_name='organization')

class Idea(models.Model):
    title=models.CharField(max_length=100, null=True)
    author=models.CharField(max_length=100, null=True)
    description=models.TextField(max_length=500, null=True)
    points=models.DecimalField(max_digits=4, decimal_places=0)
    experience=models.DecimalField(max_digits=5, decimal_places=0, null=True, default=0) 



class Comment(models.Model):
    comment=models.TextField(max_length=500, null=True)
    commenter=models.ForeignKey(Player)
    event=models.ForeignKey('charity.Event')
    date=models.DateTimeField( null=True, default=datetime.datetime.now)


class Feed(models.Model):
    player=models.ForeignKey(Player)
    event=models.ForeignKey('charity.Event')
    likes= models.DecimalField(max_digits=4, decimal_places=0, default=0)
    date=models.DateTimeField( null=True, default=datetime.datetime.now)
 


class CommentFeed(models.Model):
    comment=models.TextField(max_length=500, null=True)
    commenter=models.ForeignKey(Player)
    feed=models.ForeignKey(Feed)
    date=models.DateTimeField( null=True, default=datetime.datetime.now)



class Badge(models.Model):
    player=models.ForeignKey(Player)
    title=models.CharField(max_length=100, null=True, default='Beginner!')
    icon=models.CharField(max_length=50,choices=constants.ICON, default='fa-thumbs-o-up')

'''
def assign_badge(sender, instance, created, **kwargs):
    if created:
        badge=Badge.objects.create(player=instance.player)
        type_event=['Animals', 'Food','Art', 'Shopping', 'Elders', 'Environment']
        for tt in type_event:



        
post_save.connect(assign_badge, sender=EventHistory) '''

shop/models.py
from django.db import models
from datetime import date
from django import forms
from django.contrib.auth.models import User,UserManager
from django.utils import timezone
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _
from play.utils import *
from social_auth.models import UserSocialAuth
import play.constants
from django.core.exceptions import *
import charity.models
import play.models
# Create your models here.
import requests
import datetime
# Create your models here.
from city.models import City

class Shop(models.Model):
    user=models.ForeignKey(User)
    city=models.ForeignKey(City, related_name='city_charity', default=None, null=True)
    title=models.CharField(max_length=100, null=True, default='Super shop!')
    location=models.CharField(max_length=100, null=True)
    picture_url=models.CharField(max_length=200, null=True, default='/static/img/stanford.png')
    def __unicode__(self):  # Python 3: def __str__(self):
        return unicode(self.title) or u''   


class Coupon(models.Model):
    title=models.CharField(max_length=50, null=True)
    description=models.TextField(max_length=500, null=True)
    location=models.CharField(max_length=100, null=True)
    price=models.DecimalField(max_digits=4, decimal_places=0)
    buyers=models.ManyToManyField('play.Player', default=None, null=True)
    picture_url=models.CharField(max_length=200, null=True, default='/static/img/stanford.png')
    shop=models.ForeignKey(Shop)
    coupons_released=models.DecimalField(max_digits=4, decimal_places=0, default=10)
    def __unicode__(self):  # Python 3: def __str__(self):
        return unicode(self.title) or u'' 

def assign_coupon_pic(sender, instance, created, **kwargs):
    if created:
        instance.picture_url=instance.shop.picture_url
        instance.save()
post_save.connect(assign_coupon_pic, sender=Coupon)

play/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm,Textarea
from django import forms
from django.contrib.auth.forms import UserCreationForm
import string
from play.models import *
import constants
import datetime

class IdeaForm(ModelForm):
    title=forms.CharField()
    description=forms.CharField(widget = forms.Textarea(attrs={}))
    points=forms.DecimalField(widget = forms.TextInput(attrs={ 'size':'4'}))
    experience=forms.DecimalField(widget = forms.TextInput(attrs={ 'size':'4'}))
    class Meta:
        model=Idea
        fields = ('title','description','author','points', 'experience')

class CommentForm(ModelForm):
    comment=forms.CharField(widget = forms.Textarea) 
    class Meta:
        model=Comment
        fields = ('comment',)
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['comment'].widget.attrs['cols'] = 15
        self.fields['comment'].widget.attrs['rows'] = 1


class CommentFeedForm(ModelForm):
    comment=forms.CharField(widget = forms.Textarea) 
    class Meta:
        model=CommentFeed
        fields = ('comment', )
    def __init__(self, *args, **kwargs):
        super(CommentFeedForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['comment'].widget.attrs['cols'] = 15
        self.fields['comment'].widget.attrs['rows'] = 1


class EditUserForm(ModelForm):
    class Meta:
        model=User
        fields = ('username',)

class EditPicForm(ModelForm):
    class Meta:
        model=Player
        fields = ('picture_url', 'facebook_pic')

class SignUpForm(UserCreationForm):
    """ Require email address when a user signs up """
    email = forms.EmailField(label='Email address', max_length=75)

    def __init__(self, *args, **kwargs): 
        super(SignUpForm, self).__init__(*args, **kwargs) 
        # remove username
        self.fields.pop('username')

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name') 
        exclude=['username']

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            user = User.objects.get(email=email)
            raise forms.ValidationError("This email address already exists. Did you forget your password?")
        except User.DoesNotExist:
            return email
        
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        user.username=user.email

        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.is_active = True # change to false if using email activation
        if commit:
            user.save()

        return user

play/templates/general/layer_0.html
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="description" content="Play Palo Alto gamifies volunterring and makes you get points and discounts!">
    <meta name="author" content="francesco maria ferrari">
    <meta name="application-name" content="play palo alto">
    <meta name="keywords" content="play palo alto, palo alto, hack challenge, startup, hackpaloalto, gamification">
    <title>Play Palo Alto</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">


    <!--tiles-->


    <!-- Custom styles for this template -->
    <link href="/static/css/main.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link rel="apple-touch-icon"
      href="/static/img/logo-play.png" />
    <link rel="image_src"
      href="/static/img/logo-play.png" />
    <link rel="apple-touch-icon-precomposed"
      href="/static/img/logo-play.png" />
    <!--<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>-->
    <link rel="stylesheet" href="/static/tiles/css/final-tiles-gallery.css">

    <script src="/static/js/chart.js"></script>
    <script src="/static/tiles/js/vendor/modernizr-2.6.2.min.js"></script>
    <script src="/static/tiles/js/plugins.js"></script>
    <script src="/static/tiles/js/jquery.finalTilesGallery.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/static/tiles/js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=301965249950489&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/#"><img style="width:80px"src="/static/img/logo-play.png"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
            <li class="active"><p><a href="/#contact">Register</a> | <a href="/login">Login</a> | <a href="/idea">Send Idea</a>

            </p>


            </li> 
            {% else %}
             <li class="active"><p>
                {% block content0 %}
                {% endblock %}
                <button style="word-spacing:10px;" class="btn btn-primary btn-sm organisationButton" data-toggle="modal" data-target="#switch">
                        switch account
          </button>
        </p>
        </li>

            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
       

           {% block content1 %}
          {% endblock %}



  <div id="f"  >
    <div class="container">
      <div class="row">
         <div class="col-xs-6 col-md-4"><small>Questions or Feedback? Contact us at <a href="mailto:info@playpaloalto.com">info@playpaloalto.com</a></small></div>
          <div class="col-xs-6 col-md-4"><center><div class="fb-share-button" data-href="http://playpaloalto.com" data-width="100" data-type="button_count"></div></center></div>


      </div>
    </div>
  </div>







<!-- Modal -->
<div class="modal fade" id="switch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="addEventForm" >
      <div class="modal-header">
        <button type="button" class="close" style="color:#fff" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel" style="color: #F85C37">SWITCH BETWEEN ACCOUNTS</h3>
      </div>
      <div class=" container row modal-body">


       {% if user.player_set.all %}
       <div class="col-md-2" style="margin:10px">
          <button style="word-spacing:10px;" onClick="location.href='/{{city}}/home'"  class="btn btn-primary btn-sm organisationButton" data-toggle="modal" data-target="#switch">
                        player account
          </button>
          </div>
       {% endif %}
       {% if user.shop_set.all %}
       <div class="col-md-2" style="margin:10px">
          <button style="word-spacing:10px;" onClick="location.href='/{{city}}/shop/home'"  class="btn btn-primary btn-sm organisationButton" data-toggle="modal" data-target="#switch">
                        shop account
          </button>
          </div>
       {% endif %}
       {% if user.organization_set.all %}
       <div class="col-md-2" style="margin:10px">
          <button style="word-spacing:10px;" onClick="location.href='/{{city}}/charity/home'"  class="btn btn-primary btn-sm organisationButton" data-toggle="modal" data-target="#switch">
                        charity account
          </button>
        </div>
       {% endif %}
        </div>
      </div>
    </div>
  </div>











    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/bootstrap.js"></script>
  </body>
</html>

play/templates/general/nikos.html
<!DOCTYPE HTML>
<!--

 _   _ _____ _   _______ _____     ____________ _____ _____ _____  ___   _   _  _   _ _____ _____  
| \ | |_   _| | / /  _  /  ___|    | ___ \ ___ \  ___|  __ \_   _|/ _ \ | \ | || \ | |_   _/  ___| 
|  \| | | | | |/ /| | | \ `--.     | |_/ / |_/ / |__ | |  \/ | | / /_\ \|  \| ||  \| | | | \ `--.  
| . ` | | | |    \| | | |`--. \    | ___ \    /|  __|| | __  | | |  _  || . ` || . ` | | |  `--. \ 
| |\  |_| |_| |\  \ \_/ /\__/ /    | |_/ / |\ \| |___| |_\ \_| |_| | | || |\  || |\  |_| |_/\__/ / 
\_| \_/\___/\_| \_/\___/\____/     \____/\_| \_\____/ \____/\___/\_| |_/\_| \_/\_| \_/\___/\____/  
	                                                                      
-->

<html lang="en-GB">
<head>
	<meta charset="UTF-8">
	<title>Nikos Bregiannis</title>
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssreset/reset-min.css">
	<style type="text/css">
		a { color:#4f6b8e; text-decoration:none; }
		a:hover {color:#2f7ddd;text-decoration:underline;}
		html {text-align:center; background:#fafafa;}
		body {text-align:left; color:#111;font-family: 'Consolas', Helvetica, Arial sans-serif;
			line-height:18px; font-size:13px; position:absolute; top:-30px; left:0px; overflow:hidden; height:100%; width:100%;}

		img.main {position:absolute; top:30px;  right:0px; height:100%; z-index:100; padding-left:1px; border-left:1px solid grey;
				  filter: url("data:image/svg+xml;utf8,<svg></svg>#grayscale"); filter: gray; -webkit-filter: grayscale(1); }
		img.main:hover {filter:none;  -webkit-filter: grayscale(0);}
		#main {height:100%; width:30%; overflow:hidden;
			position:absolute; left:0px; top:0px; padding:10% 10px 10% 10%; z-index:200; background:#fafafa; background:rgba(250,250,250,.8);}

		
		h1 {font-size:30px; line-height:36px; margin-bottom:0px; font-weight:700; font-family:"Consolas"; top:-10px;}
    	h2 {font-size:14px; letter-spacing: 2px; text-transform:uppercase; margin-bottom:18px; font-family:"Consolas";}
		h3 {font-size:18px; line-height:18px; margin-bottom:20px; font-family:"Consolas";}
		
		p, ul {margin-bottom:18px;}
		
		ul {margin-left:1em; margin-bottom:36px;}
		ul li {list-style-type:circle; margin-bottom:5px;}
		ul strong {font-weight:300; display:inline-block; width:80px;}
		ul strong:first-letter {font-weight:normal;}
		ul em.hint {display:inline-block;margin:0 20px; color:gray;}
        
        img.book{ filter: url("data:image/svg+xml;utf8,<svg></svg>#grayscale"); filter: gray; -webkit-filter: grayscale(1); }
        img.book:hover {filter:none;  -webkit-filter: grayscale(0);}
		</style>
</head>
<body>
	<div id="main">
		<h1 id="nikos_bregiannis">Nikos Bregiannis</h1>
    	<h2>Network and Software Engineer</h2>
		<h3>Get in touch&hellip;</h3>
		<ul>
			<li>
				<strong>Phone:</strong>
				<a href="callto:0014082163980" title="Double-click to call..." id="phone">+1&nbsp;(408)&nbsp;216-3980</a>
				<t>/</t>
				<a href="callto:00306944320067" title="Double-click to call..." id="phone">+30&nbsp;(694)&nbsp;432-0067</a>
			</li>
			<li>
				<strong>Email:</strong>
				<a href="mailto:nikos.bre@gmail.com" 
					 title="Double-click to send me an email..." id="email">nikos.bre@gmail.com</a>
			</li>
		</ul>
		
		<h3>Find out more about me&hellip;</h3>
		<ul>
			<li>
				<strong>CV:</strong>
				<a href="nikos_bregiannis.pdf">nikos_bregiannis.pdf</a>
			</li>
			<li>
				<strong>Facebook:</strong>
				<a href="http://facebook.com/nikos.bre">facebook.com/nikos.bre</a>
			</li>
			<li>
				<strong>LinkedIn:</strong>
				<a href="https://www.linkedin.com/in/nikosbregiannis">linkedin.com/in/nikosbregiannis</a>
			</li>
		</ul>

        <h3>Recent projects&hellip;</h3>
        <a href="http://playpaloalto.com" target="_blank">
            <img style="margin-bottom:20px;" width="140" class="book" src="./img/logo-play.png" alt="Play Palo Alto" />
        </a>
        
        <h3>Education&hellip;</h3>
        <a href="http://www.ee.ucl.ac.uk" target="_blank">
            <img width="120" class="book" src="./img/logo.gif" alt="Univeristy College London" />
        </a>
        <a href="http://ece.ntua.gr" target="_blank">
            <img style="margin-bottom:-15px;" width="100" class="book" src="./img/pyrforos.gif" alt="National Technical University of Athens" />
        </a>
	</div>



	<img class="main" src="./img/try.jpg" alt="Nikos Bregiannis (photo: Victoria Guseva)" />







	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" charset="utf-8">
		$(function(){
			
			/*
			 * Make mailto: and callto: links more user-friendly
			 */
			var hints = {"email":false,"phone":false};
			$("a[href^='mailto:'], a[href^='callto:']")
				.bind('click', function(e){
					var id = $(this).attr('id');
					if(!hints[id]){
						$(this).parent("li").append($('<em class="hint">'+$(this).attr('title')+'</em>'));
						hints[id] = setTimeout(function(){
							$("em.hint").fadeTo("fast", 0, function(){ 
								$(this).remove();
								hints[id] = false; });
						}, 2000);
						e.preventDefault();
					}
					
				})			
			/*
			 * Turn callto: into tel: links for mobile visitors
			 */
			if( (navigator.platform.indexOf("iPhone") != -1) || 
				(navigator.platform.indexOf("iPod") != -1) ||
		 		(navigator.userAgent.toLowerCase().indexOf("android") != -1) ){
					$('a[title*="click"]').each(function(){
						$(this).attr('title', $(this).attr('title').replace(/click/ig, "tap"))
					});
					$('a[href^="callto:"]').each(function(){
						$(this).attr('href', $(this).attr('href').replace(/callto/, "tel"))
					})
			}

		})


	/**
	 * Google Analytics
	 */
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-74600-16']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</body>
</html>